name: Keep All Services Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes

jobs:
  ping-services:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Eureka Server
        run: curl -s https://ecommerce-eureka-service.onrender.com/actuator/health
      
      - name: Ping Product Service
        run: curl -s https://ecommerce-product-service-7u88.onrender.com/actuator/health

      - name: Ping Inventory Service
        run: curl -s https://ecommerce-inventory-service.onrender.com/actuator/health

      - name: Ping Order Service
        run: curl -s https://ecommerce-order-service.onrender.com/actuator/health

